name: Deploy to EC2 

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            APP_NAME="drbuddy-app"
            CONTAINER_NAME="drbuddy-app-container"
            PROJECT_DIR="/home/ec2-user/DrBuddy"

            echo "Removing old project directory"
            rm -rf $PROJECT_DIR

            echo "Cloning fresh repository"
            git clone -b main https://${{ secrets.PAT_GITHUB }}@github.com/akshitverma317/DrBuddy.git $PROJECT_DIR

            cd $PROJECT_DIR

            echo "Stopping and removing old container if exists"
            sudo docker stop $CONTAINER_NAME || true
            sudo docker rm $CONTAINER_NAME || true

            echo "Removing old image (optional)"
            sudo docker rmi $APP_NAME || true

            echo "Building new Docker image"
            sudo docker build -t $APP_NAME .

            echo "Running new container"
            sudo docker run -d \
              --name $CONTAINER_NAME \
              -p 5000:5000 \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
              -e PINECONE_API_KEY="${{ secrets.PINECONE_API_KEY }}" \
              -e GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
              $APP_NAME

            echo "Deployment completed successfully"
